<h1>This template is generated by Blade</h1>
<ul>
@foreach($user as $key => $value)
    <li>{{ $key }} : {{ $value }}</li>
@endforeach
</ul>
<img src="{{ themosis_theme_assets().'/images/img.jpg' }}" alt="this is an image"/>
<a href="{{  }}">Go to contact page</a>